<?php

  function brainjogging_report_menu() {
    
    $items['admin/brainjogging/report'] = array(
   'title' => 'Reports',
   'type' => MENU_NORMAL_ITEM,
   'page callback' => 'general_report',
   'page arguments' => array('create'),
   'access callback' => 'check_user',
   
  
  );
    $items['admin/brainjogging/report/general'] = array(
    'title' => t('General Report'), 
    'page callback' => 'general_report',
    'page arguments' => array('create'),
    'access callback' => 'check_user',
    'type' => MENU_LOCAL_TASK,
    'file' => 'general_report.inc',
    
  );
   $items['admin/brainjogging/report/general_report/%'] = array(
    'page callback' => 'general_report',
    'page arguments' => array('list'),
    'access callback' => 'check_user',
    'file' => 'general_report.inc',
    
  );
     $items['admin/brainjogging/report/letter_flash_missed_letters'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => t('letter flash missed  info'), 
    'page callback' => 'letter_flash_missed_letter_report',
    'page arguments' => array('create'),
    'access callback' => 'check_user',
    'file' => 'letter_flash_missed_letters.inc',
    
  );
     $items['admin/brainjogging/report/letter_flash_missed_letters_report/%'] = array(
    
    'page callback' => 'letter_flash_missed_letter_report',
    'page arguments' => array('list'),
    'access callback' => 'check_user',
    'file' => 'letter_flash_missed_letters.inc',
    
  );
   $items['admin/brainjogging/report/word_flash_missed_words'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' =>t('Word flash missed  info'), 
    'page callback' => 'word_flash_missed_word_report',
    'page arguments' => array('create'),
    'access callback' => 'check_user',
    'file' => 'word_flash_missed_words.inc',
    
  );
    $items['admin/brainjogging/report/word_flash_missed_words_report/%'] = array(
    'page callback' => 'word_flash_missed_word_report',
    'page arguments' => array('list'),
    'access callback' => 'check_user',
    'file' => 'word_flash_missed_words.inc',
    
  );
    $items['admin/brainjogging/report/total_activity_completed'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' =>t('Completed activity  info'), 
    'page callback' => 'total_activity_completed_report',
    'page arguments' => array('create'),
    'access callback' => 'check_user',
    'file' => 'total_activity_completed.inc',
    
  );
    $items['admin/brainjogging/report/total_activity_completed_report/%'] = array(
    'page callback' => 'total_activity_completed_report',
    'page arguments' => array('list'),
    'access callback' => 'check_user',
    'file' => 'total_activity_completed.inc',
    
  );
 $items['admin/brainjogging/report/eye_move_wordlist'] = array(
  'type' => MENU_LOCAL_TASK,
    'title' =>t('Eye Movement Wordlist  info'), 
    'page callback' => 'eye_move_wordlist_report',
    'page arguments' => array('create'),
    'access callback' => 'check_user',
    'file' => 'eye_move_wordlist.inc',
    
  );
    $items['admin/brainjogging/report/eye_move_wordlist_report/%'] = array(
    'page callback' => 'eye_move_wordlist_report',
    'page arguments' => array('list'),
    'access callback' => 'check_user',
    'file' => 'eye_move_wordlist.inc',
    
  );
    $items['admin/brainjogging/report/lf_client_response'] = array(
      
    'title' =>t('Letter Flash Client Response  info'), 
    'page callback' => 'lf_client_response_report',
    'page arguments' => array('create'),
    'access callback' => 'check_user',
    'file' => 'lf_client_response.inc',
    
  );
    $items['admin/brainjogging/report/lf_client_response_report/%'] = array(
    'page callback' => 'lf_client_response_report',
    'page arguments' => array('list'),
    'access callback' => 'check_user',
    'file' => 'lf_client_response.inc',
    
  );
    
    
    return $items;
  }

  function check_user() { 	
	global $user; 	 	
  if(in_array('site administrator',$user->roles) || in_array('teacher',$user->roles) )
    {
			
		return TRUE; 	
	} 	 	
 
	return FALSE; 
} 

?>