<?php

  function brainjogging_report_menu() {
    
    $items['admin/brainjogging/report'] = array(
   'title' =>t('Reports'),
   'type' => MENU_NORMAL_ITEM,
   'access arguments' => array('bj common reports'),
   
  
  );
    $items['admin/brainjogging/report/general'] = array(
    'title' => t('General Report'), 
    'page callback' => 'general_report',
    'page arguments' => array('create'),
    'access arguments' => array('bj admin reports'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'general_report.inc',
    
  );
   $items['brainjogging/report/general_report'] = array(
    'page callback' => 'general_report',
    'type' => MENU_NORMAL_ITEM,
    'page arguments' => array('list'),
    'access arguments' =>array('bj admin reports'),
    'weight'=> 1,
    'file' => 'general_report.inc',
    
  );
     $items['admin/brainjogging/report/letter_flash_missed_letters'] = array(
    'title' => t('Letter flash missed  info'), 
    'page callback' => 'letter_flash_missed_letter_report',
    'page arguments' => array('create'),
    'access arguments' => array('bj common reports'),
    'file' => 'letter_flash_missed_letters.inc',
    
  );
     $items['brainjogging/report/letter_flash_missed_letters_report'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'letter_flash_missed_letter_report',
    'page arguments' => array('list'),
    'access arguments' => array('bj common reports'),
    'file' => 'letter_flash_missed_letters.inc',
    
  );
   $items['admin/brainjogging/report/word_flash_missed_words'] = array(
    'title' =>t('Word flash '), 
    'page callback' => 'word_flash_missed_word_report',
    'page arguments' => array('create'),
    'access arguments' => array('bj common reports'),
    'file' => 'word_flash_missed_words.inc',
    
  );
    $items['brainjogging/report/word_flash_missed_words_report'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'word_flash_missed_word_report',
    'page arguments' => array('list'),
    'access arguments' => array('bj common reports'),
    'file' => 'word_flash_missed_words.inc',
    
  );
    $items['admin/brainjogging/report/total_activity_completed'] = array(
    'title' =>t('Completed activity '), 
    'page callback' => 'total_activity_completed_report',
    'page arguments' => array('create'),
    'access arguments' => array('bj common reports'),
    'file' => 'total_activity_completed.inc',
    
  );
    $items['brainjogging/report/total_activity_completed_report'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'total_activity_completed_report',
    'page arguments' => array('list'),
    'access arguments' => array('bj common reports'),
    'file' => 'total_activity_completed.inc',
    
  );
 $items['admin/brainjogging/report/eye_move_wordlist'] = array(
    'title' =>t('Eye Movement'), 
    'page callback' => 'eye_move_wordlist_report',
    'page arguments' => array('create'),
    'access arguments' => array('bj common reports'),
    'file' => 'eye_move_wordlist.inc',
    
  );
    $items['brainjogging/report/eye_move_wordlist_report'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'eye_move_wordlist_report',
    'page arguments' => array('list'),
    'access arguments' => array('bj common reports'),
    'file' => 'eye_move_wordlist.inc',
    
  );
    $items['admin/brainjogging/report/lf_client_response'] = array(
    'title' =>t('Letter Flash Client Response  '), 
    'page callback' => 'lf_client_response_report',
    'page arguments' => array('create'),
    'access arguments' => array('bj common reports'),
    'file' => 'lf_client_response.inc',
    
  );
    $items['brainjogging/report/lf_client_response_report'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'lf_client_response_report',
    'page arguments' => array('list'),
    'access arguments' => array('bj common reports'),
    'file' => 'lf_client_response.inc',
    
  );
    
    
    return $items;
  }

  function brainjogging_report_perm() { 	
  return array('bj admin reports','bj common reports');
} 

?>