<?php

function brainjogging_test_theme(){
  return array(
    'bj_dashboard' => array(
      'arguments' => array('vars' => NULL),
      'template'  => 'bj-dashboard',
    ),
    'bj_eye_movement' => array(
      'arguments' => array('vars' => NULL),
      'template'  => 'bj-eye-movement',
    ),
    'bj_letter_flash' => array(
      'arguments' => array('vars' => NULL),
      'template'  => 'bj-letter-flash',
    ),
    'bj_word_flash' => array(
      'arguments' => array('vars' => NULL),
      'template'  => 'bj-word-flash',
    ),
  );
}

function brainjogging_test_menu(){
  $items['brainjogging/test/dashboard'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('brainjogging_test_dashboard'),
    'access callback' => TRUE,
  );
  $items['brainjogging/test/eye_movement'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('brainjogging_test_eye_movement'),
    'access callback' => TRUE,
    'file' => 'letter_flash.inc',
    
  );
  $items['brainjogging/test/letter_flash'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('brainjogging_test_letter_flash'),
    'access callback' => TRUE,
  );
  $items['brainjogging/test/word_flash'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('brainjogging_test_word_flash'),
    'access callback' => TRUE,
  );
    $items['brainjogging/submit'] = array(
    'page callback' => 'letter_flash_submit',
    'page arguments' => array('list'),
    'access callback' => TRUE,
    'file' => 'letter_flash.inc',
  );
     $items['brainjogging/wordflash'] = array(
    'page callback' => 'word_flash_submit',
    'page arguments' => array('list'),
    'access callback' => TRUE,
    'file' => 'word_flash.inc',
  );
  return $items;
}

function brainjogging_test_dashboard(){
  $path = drupal_get_path('module', 'brainjogging_test');
  drupal_add_css($path . '/css/bj_test_style.css', 'module', 'all', FALSE);
  $form = array();
  $form['dashboard'] = array(
    '#value' => theme('bj_dashboard',array('path'=>drupal_get_path('module', 'brainjogging_test')))
  );
  return $form;
}

function brainjogging_test_eye_movement(){
  
  $res=db_query("SELECT t1.body, t1.nid FROM node_revisions t1, bj_wordlist_relativity t2 WHERE t2.type=1 and  t1.nid=t2.wl_id");
  $eyeinput=array();
  while($row=mysql_fetch_array($res)){
    $eyeinput['nid'][]  = $row['nid'];
    $eyeinput['input'][] = $row['body'];
  }
  $rand_keys = array_rand($eyeinput['input'], 3);
  drupal_add_js(array('input1'=> $eyeinput['input'][$rand_keys[0]]),'setting');
  drupal_add_js(array('input2'=> $eyeinput['input'][$rand_keys[1]]),'setting');
  drupal_add_js(array('input2'=> $eyeinput['input'][$rand_keys[2]]),'setting');
 //drupal_add_js(array('name'=>'gobi'),'setting');
  
  bj_add_js();
  drupal_add_js("
    jQuery(document).ready(function () {
      BrianJogging.eyemomvent.initialize();
    });",
    'inline'
  );
  $form = array();
  $form['eye_movement'] = array(
    '#value' => theme('bj_eye_movement',array('path'=>drupal_get_path('module', 'brainjogging_test')))
  );
  return $form;
}

function brainjogging_test_letter_flash(){
  bj_add_js();
  drupal_add_js("
    jQuery(document).ready(function () {
      init = {
        highest_level : 1,
        missed_letter : ['a','e','i','o','u'],
        missed_letter_reinforcement : ".variable_get('missed_letters_reinforcement',"50").",
        change_case : 0,
        show_start_from_same_level : ".variable_get('start_from_same_level_per',"50").",
      };
      BrianJogging.letter_flash.initialize(init);
    });",
    'inline'
  );
  $form = array();
  $form['letter_flash'] = array(
    '#value' => theme('bj_letter_flash',array('path'=>drupal_get_path('module', 'brainjogging_test')))
  );
  return $form;
}

function brainjogging_test_word_flash(){
  bj_add_js();
  drupal_add_js("
    jQuery(document).ready(function () {
      BrianJogging.wordflash.initialize();
    });",
    'inline'
  );
  $form = array();
  $form['word_flash'] = array(
    '#value' => theme('bj_word_flash',array('path'=>drupal_get_path('module', 'brainjogging_test')))
  );
  return $form;
}

function bj_add_js(){
  $path = drupal_get_path('module', 'brainjogging_test');
  drupal_add_css($path . '/css/bj_test_style.css', 'module', 'all', FALSE);
  drupal_add_js($path . '/js/libs/handlebars.1.0.0.beta.3.js');
  drupal_add_js($path . '/js/libs/jquery_plugins.js');
  drupal_add_js($path . '/js/application.js');
}

function brainjogging_test_user($op, &$edit, &$account, $category = NULL) {
  if ( $op == 'login' ) {
    $_REQUEST['destination'] = 'brainjogging/test/eye_movement';
  }
}